name: Environments
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: false
        description: Environment name

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.NAME }}
      PASSWORD: ${{ secrets.NAME }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
